### ISSUE TITLE
Small issue with models not existing on first run

### ISSUE THREAD

**Issue by melMass** [diontimmer/Sample-Diffusion-ComfyUI-Extension#7]
Hi, thanks for this extension.

A small issue is that it errors out OOB because it looks for `custom_nodes/SampleDiffusion/libs`, the script should probably create that dir if missing

```ruby
Traceback (most recent call last):
  File "ComfyUI.git\nodes.py", line 1384, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "ComfyUI.git\custom_nodes\SampleDiffusion\__init__.py", line 9, in <module>
    node_import = importlib.import_module('custom_nodes.SampleDiffusion.' + node)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "ComfyUI.git\custom_nodes\SampleDiffusion\__init__.py", line 9, in <module>
    node_import = importlib.import_module('custom_nodes.SampleDiffusion.' + node)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "ComfyUI.git\custom_nodes\SampleDiffusion\EXT_SampleDiffusion.py", line 111, in <module>
    if not os.path.exists(os.path.join(comfy_dir, 'custom_nodes/SampleDiffusion/libs')):
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.10.11\lib\ntpath.py", line 104, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by melMass** [comment]
Ohhh... that was not the issue at all.
The issue is here https://github.com/diontimmer/Sample-Diffusion-ComfyUI-Extension/blob/224f9bc10e77bc45d9bf6678d70c7f5b688b7b5b/SampleDiffusion/EXT_SampleDiffusion.py#L28-L39

my folder is not named `ComfyUI`

**Comment by melMass** [comment]
Probably doing `git rev-parse --show-toplevel` is safer, but not a big deal
