### ISSUE TITLE
Unable to install the extension in New ComfyUI updates

### ISSUE THREAD

**Issue by jags111** [diontimmer/Sample-Diffusion-ComfyUI-Extension#8]
We have followed the step by step procedure as mentioned in this repo to install the extension inside comfyUI- CustomNodes- SampleDiffusion --- a copy of the sample diffusion from the repo. We also copied the JS file to web extensions and still not able to get this to work as none of the nodes show up in the UI.
Can you please suggest a workaround for same or suggest some changes so it can get loaded into comfyUI. Also please if you can add this to ComfyUI- Manager and inform Dr.LT data on same it will be super cool. Please advise ASAP as this is the only module for generating audio inside COMFYUI.

Thanks for your feedback

**Comment by jags111** [comment]
By the by the VEXTRA nodes are loading without any issues and if same can be done for this it will be awesome.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SampleDiffusion\__init__.py", line 9, in <module>
    node_import = importlib.import_module('custom_nodes.SampleDiffusion.' + node)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

Cannot import D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SampleDiffusion module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
